name: FTP Deploy

on:
  push:
    branches: [ "main" ]   # đổi nếu bạn dùng branch khác

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Nếu dự án có bước build (React/Vite/SCSS...), build tại đây
      # rồi set local-dir tới thư mục build (vd: ./dist).
      # InfinityFree không có Node/Composer runtime.
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      # - name: Install deps & Build
      #   run: |
      #     npm ci
      #     npm run build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          # Nếu bạn có thư mục build, đổi thành ./dist hoặc ./build
          local-dir: ./
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/.env
            **/*.log
            wp-content/uploads/**
            wp-content/cache/**
