name: 🚀 Deploy to orionimoi.wuaze.com

on:
  push:
    branches: [ "main" ]
    paths:
      - '**'         # hoặc thu hẹp: 'themes/**', 'plugins/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy wp-content
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/ex/ORIONI/wp-content/   # THƯ MỤC TRÊN HOST
          local-dir: ./                               # ROOT REPO = wp-content
          state-name: wp-content-orioni               # để lần sau chỉ up file đổi
          timeout: 600000
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/.env
            **/*.log
            **/debug.log
            upgrade/**
            upgrade-temp-backup/**